### ISSUE TITLE
After save Shift-JIS file, character corruption when I put a focus into a divided window

### ISSUE THREAD

**Issue by h0kut0** [seanliang/ConvertToUTF8#51]
Thank you for this plugin.
About the matter of the title, please refer to video.
[![](http://img.youtube.com/vi/PkKti1UCAtQ/0.jpg)](https://www.youtube.com/watch?v=PkKti1UCAtQ?vq=highres)

**Comment by seanliang** [comment]
I can't reproduce this problem, would you please press ctrl + ` and paste the log here?

![columns](https://cloud.githubusercontent.com/assets/1852862/7152449/bfcee044-e36e-11e4-8a0f-f6bae3501964.gif)

**Comment by h0kut0** [comment]
nmmm :weary:
thank you for replay.

# log
When I opened up an English text encoded in shift-jis.
```cmd
unknown include #documentation
```

When I opened up a Japanese text encoded in shift-jis.
```cmd
SublimeLinter: htmltidy activated: C:\Users\h.kato\Dropbox\settings\SublimeText3\bin\tidy.exe 
SublimeLinter: jshint activated: C:\Users\h.kato\AppData\Roaming\npm\jshint.cmd 
SublimeLinter: csslint activated: C:\Users\h.kato\AppData\Roaming\npm\csslint.cmd 
SublimeLinter: php activated: C:\PHP\v5.5\php.exe 
unable to auto detect encoding for C:\xampp\htdocs\shiftjis_test\shiftjis_jp.txt, using fallback encoding UTF-8
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "trailing_spaces in C:\Users\h.kato\AppData\Roaming\Sublime Text 3\Installed Packages\TrailingSpaces.sublime-package", line 419, in on_activated
  File "trailing_spaces in C:\Users\h.kato\AppData\Roaming\Sublime Text 3\Installed Packages\TrailingSpaces.sublime-package", line 440, in freeze_last_version
  File "./codecs.py", line 680, in read
  File "./codecs.py", line 483, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
```

When I saved a Japanese text encoded in shift-jis.
```cmd
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 240, in on_pre_save
    callback.on_pre_save(v)
  File "trailing_spaces in C:\Users\h.kato\AppData\Roaming\Sublime Text 3\Installed Packages\TrailingSpaces.sublime-package", line 424, in on_pre_save
  File "trailing_spaces in C:\Users\h.kato\AppData\Roaming\Sublime Text 3\Installed Packages\TrailingSpaces.sublime-package", line 440, in freeze_last_version
  File "./codecs.py", line 680, in read
  File "./codecs.py", line 483, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
```

When I moved the focus to divided other window.
```cmd
unable to auto detect encoding for C:\xampp\htdocs\shiftjis_test\shiftjis_jp.txt, using fallback encoding UTF-8
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 320, in on_deactivated
    callback.on_deactivated(v)
  File "C:\Users\h.kato\AppData\Roaming\Sublime Text 3\Packages\ConvertToUTF8\ConvertToUTF8.py", line 765, in on_deactivated
    os.chmod(tmp_name, os.stat(file_name)[0])
FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。: 'C:\\Users\\h.kato\\AppData\\Roaming\\Sublime Text 3\\Packages\\User\\c2u_tmp\\1fe1aaff502fc6b4b378b9602af59b67'
```

# video
[![](http://img.youtube.com/vi/08LNSBHDKZ8/0.jpg)](https://www.youtube.com/watch?v=08LNSBHDKZ8)

I am sorry to trouble you, but I would really appreciate it if you could confirm.

**Comment by seanliang** [comment]
The UnicodeDecodeErrors are caused by TrailingSpaces, since it treats encoding of every file as UTF-8. I've tried to install TrailingSpaces, but still can't reproduce this problem.

To solve it, please follow the steps:
1. Disable `TrailingSpaces` (via Package Control), if the problem still exists, then
2. Disable any other 3rd plugins temporary, if the problem still exists, then
3. Change `lazy_reload` to `false` in User settings of ConvertToUTF8

**Comment by h0kut0** [comment]
By the step 1, it was able to be settled!!!!

> Disable `TrailingSpaces` (via Package Control)

Thank you very much for taking the time.
This plug-in is so important to me.
I wish you will be successful.

**Comment by seanliang** [comment]
That's great. Let me know if you have any other question.
