### ISSUE TITLE
KeyError: 'convert_on_find' on Sublime Text start up

### ISSUE THREAD

**Issue by evandrocoan** [seanliang/ConvertToUTF8#77]
This error pops on my console when Sublime Text build 3136 starts:
```
plugins loaded
Traceback (most recent call last):
  File "D:\SublimeText\sublime_plugin.py", line 330, in on_new
    callback.on_new(v)
  File "D:\SublimeText\Data\Packages\ConvertToUTF8\ConvertToUTF8.py", line 638, in on_new
    if get_setting(view, 'default_encoding_on_create'):
  File "D:\SublimeText\Data\Packages\ConvertToUTF8\ConvertToUTF8.py", line 144, in get_setting
    return view.settings().get(key, SETTINGS[key]);
KeyError: 'default_encoding_on_create'
Traceback (most recent call last):
  File "D:\SublimeText\sublime_plugin.py", line 389, in run_callback
    expr()
  File "D:\SublimeText\sublime_plugin.py", line 488, in <lambda>
    run_callback('on_modified', callback, lambda: callback.on_modified(v))
  File "D:\SublimeText\Data\Packages\ConvertToUTF8\ConvertToUTF8.py", line 730, in on_modified
    if get_setting(view, 'convert_on_find') and self.is_find_results(view):
  File "D:\SublimeText\Data\Packages\ConvertToUTF8\ConvertToUTF8.py", line 144, in get_setting
    return view.settings().get(key, SETTINGS[key]);
KeyError: 'convert_on_find'
Traceback (most recent call last):
  File "D:\SublimeText\sublime_plugin.py", line 389, in run_callback
    expr()
  File "D:\SublimeText\sublime_plugin.py", line 488, in <lambda>
    run_callback('on_modified', callback, lambda: callback.on_modified(v))
  File "D:\SublimeText\Data\Packages\ConvertToUTF8\ConvertToUTF8.py", line 730, in on_modified
    if get_setting(view, 'convert_on_find') and self.is_find_results(view):
  File "D:\SublimeText\Data\Packages\ConvertToUTF8\ConvertToUTF8.py", line 144, in get_setting
    return view.settings().get(key, SETTINGS[key]);
KeyError: 'convert_on_find'
```

**Comment by evandrocoan** [comment]
Also happened on linux mint 18 sarah. Full start up log:

1. [ConvertToUTF8_convert_on_find.txt](https://gist.github.com/evandrocoan/f528adee56c4bfa12ed2d0dcf55ba6a4)
